### ISSUE TITLE
Using in SciPy?

### ISSUE THREAD

**Issue by david-cortes** [wilmerhenao/L-BFGS-B-NS#1]
I noticed that you took the lbfgsb.f file from scipy for this implementation, and I’m wondering if there’s some easy way of calling L-BFGS-B-NS from scipy in Python.

I tried replacing the file `lbfgsb.f` in `scipy/optimize/lbfgsb_src/` with the `lbfgsbNS.f90`, changed the reference to `lbfgsb.f` to the new file name in `scipy/optimize/setup.py` and `scipy/optimize/lbfgsb_src/lbfgsb.pyf`, but after compiling it, it just segfaults when I try to call it from `scipy.optimize.minimize`.

EDIT: managed to make it work, noticed in the end that variables like `task` are modified in-place rather than being returned and that's why scipy failed. Will submit a modified wrapper in case you're interested.

**Comment by wilmerhenao** [comment]
I actually didn't get it from Scipy. I got the files from professor Jorge Nocedal back in 2012 I think. Then, Scipy took his file and included it within their tools.
